// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ3nEy6iA1kUnaCCrES9pZn5Nato3Wjg0',
    appId: '1:51418488780:web:831390bac50e6f4d860769',
    messagingSenderId: '51418488780',
    projectId: 'chatt-app-6c911',
    authDomain: 'chatt-app-6c911.firebaseapp.com',
    storageBucket: 'chatt-app-6c911.firebasestorage.app',
    measurementId: 'G-4VD1574JH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr3NvP96bKy3nrBOCIFx3yK5wiqGNE70Q',
    appId: '1:51418488780:android:627ec0617ba40525860769',
    messagingSenderId: '51418488780',
    projectId: 'chatt-app-6c911',
    storageBucket: 'chatt-app-6c911.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFu9Xn3helXocw-CH2NPdiyudBhsDZuPc',
    appId: '1:51418488780:ios:99561b1fc5e8fe3e860769',
    messagingSenderId: '51418488780',
    projectId: 'chatt-app-6c911',
    storageBucket: 'chatt-app-6c911.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFu9Xn3helXocw-CH2NPdiyudBhsDZuPc',
    appId: '1:51418488780:ios:99561b1fc5e8fe3e860769',
    messagingSenderId: '51418488780',
    projectId: 'chatt-app-6c911',
    storageBucket: 'chatt-app-6c911.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ3nEy6iA1kUnaCCrES9pZn5Nato3Wjg0',
    appId: '1:51418488780:web:95b0b8f77ab640ac860769',
    messagingSenderId: '51418488780',
    projectId: 'chatt-app-6c911',
    authDomain: 'chatt-app-6c911.firebaseapp.com',
    storageBucket: 'chatt-app-6c911.firebasestorage.app',
    measurementId: 'G-09Y7LBVYX0',
  );
}
